# Generated by Django 3.1.3 on 2020-12-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationHLCG', '0002_gameresult_gamesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
